---
- name: Build AdGuardHome
  hosts: localhost
  gather_facts: false
  vars:
    gh_ws: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}"
    repo: 'AdguardTeam/AdGuardHome'
    pkg_name: 'adguardhome'
    config: '{{ gh_ws }}/repo/pkgs/{{ pkg_name }}/config.yml'
  tasks:
    - name: Install pkg-repo-tools
      ansible.builtin.pip:
        name: file://{{ gh_ws }}/repo/.github/assets

    - name: Create Directories
      ansible.builtin.file:
        path: "{{ gh_ws }}/dist/pkg"
        state: directory
        recurse: true
        mode: '0755'

    - name: Install snapcraft
      ansible.builtin.command:
        cmd: snap install snapcraft --classic
        creates: "/snap/bin/snapcraft"
      become: true

    - name: Get release from config
      ansible.builtin.command:
        cmd: "yq '.pkg_manifest.version' {{ config }}"
      register: latest_release
      changed_when: latest_release.rc != 0

    - name: Git checkout repository
      ansible.builtin.git:
        repo: 'https://github.com/{{ repo }}.git'
        dest: "{{ gh_ws }}/src"
        version: "{{ latest_release.stdout }}"

    - name: Build AdGuardHome
      community.general.make:
        chdir: "{{ gh_ws }}/src"
        target: build-release
        params:
          VERBOSE: 1
          CHANNEL: release
          SIGN: 0
          VERSION: "{{ latest_release.stdout }}"
          DIST_DIR: "./dist"
          ARCH: "{{ lookup('env', 'ARCH',) }}"
          OS: freebsd

    - name: Create Directories
      ansible.builtin.file:
        path: "{{ gh_ws }}/dist/pkg/{{ item }}"
        state: directory
        recurse: true
        mode: '0755'
      loop:
        - 'opt/{{ pkg_name }}'
        - 'etc/rc.d'

    - name: Copy Binary
      ansible.builtin.copy:
        src: "{{ gh_ws }}/src/dist/AdGuardHome_freebsd_{{ lookup('env', 'ARCH',) }}/AdGuardHome/AdGuardHome"
        dest: "{{ gh_ws }}/dist/pkg/opt/{{ pkg_name }}/{{ pkg_name }}"
        remote_src: true
        mode: '0755'

    - name: Copy License
      ansible.builtin.copy:
        src: "{{ gh_ws }}/src/LICENSE.txt"
        dest: "{{ gh_ws }}/dist/pkg/opt/{{ pkg_name }}/LICENSE"
        remote_src: true
        mode: '0644'

    - name: Provide a link to the Source Code
      ansible.builtin.copy:
        content: |
          This software is licensed under the GNU General Public License, Version 3.
          You may obtain a copy of the original source code at:
          https://github.com/{{ repo }}/archive/refs/tags/{{ latest_release.stdout }}.tar.gz
        dest: "{{ gh_ws }}/dist/pkg/opt/{{ pkg_name }}/SOURCE"
        mode: '0644'

    - name: Create Service
      ansible.builtin.shell:
        cmd: |
          pkg-tool create-service {{ config }}
        chdir: "{{ gh_ws }}/dist/pkg/etc/rc.d/"
        creates: "{{ gh_ws }}/dist/pkg/etc/rc.d/{{ pkg_name }}"

    - name: Create Manifest
      ansible.builtin.shell:
        cmd: |
          pkg-tool create-manifest {{ config }} \
            --abi ${ABI} --arch ${ARCH}
        chdir: "{{ gh_ws }}/dist/"
        creates: "{{ gh_ws }}/dist/+MANIFEST"

    - name: Create PKG # noqa: command-instead-of-module
      ansible.builtin.shell: # noqa: risky-shell-pipe
        cmd: |
          tar -cf {{ pkg_name }}-{{ latest_release.stdout[1:] }}.pkg \
            --zstd \
            --owner=0 \
            --group=0 \
            --transform 's|^pkg||' \
            +COMPACT_MANIFEST +MANIFEST $(find pkg -type f)
        chdir: "{{ gh_ws }}/dist"
        creates: "{{ gh_ws }}/dist/{{ pkg_name }}-{{ latest_release.stdout[1:] }}.pkg"

    - name: Create Packagesite Info
      ansible.builtin.shell:
        cmd: |
          pkg-tool create-packagesite-info ./+COMPACT_MANIFEST
        chdir: "{{ gh_ws }}/dist"
        creates: "{{ gh_ws }}/dist/packagesite_info.json"

    - name: Remove intermediate PKG Folder
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ gh_ws }}/dist/+MANIFEST"
        - "{{ gh_ws }}/dist/+COMPACT_MANIFEST"
        - "{{ gh_ws }}/dist/pkg"
