version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directories:
    - "pkg-tool"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      python:
        patterns: ["*"]
