---
build_config:
  include:
    go: '1.23'
    node: '22'
pkg_manifest:
  name: prometheus
  origin: mietzen/prometheus
  version: 3.1.0
  comment: The Prometheus monitoring system and time series database.
  www: https://prometheus.io/
  maintainer: github.nstein@mailbox.org
  prefix: /opt/prometheus
  users:
    - prometheus
  groups:
    - www
  licenselogic: single
  licenses:
    - Apache-2.0 license
  desc: |
    Prometheus is an open-source monitoring system and time series database designed for reliability and scalability.
    It collects metrics from configured targets via HTTP endpoints, stores them in a time series database, and enables powerful querying with PromQL.
    Prometheus features multi-dimensional data collection, built-in alerting, service discovery, and federation.
    It operates independently without external storage dependencies, making it ideal for cloud-native environments.
    Originally developed at SoundCloud, it is now a CNCF project widely used for monitoring distributed systems.
  scripts:
    post-install: |
      chown root:wheel /etc/rc.d/prometheus
      echo 'prometheus_enable="YES"' >> /etc/rc.conf
pkg_service:
  template: default
  vars:
    command: /opt/prometheus/prometheus --config.file=config.yml
