---
- name: Redistribute htop
  hosts: localhost
  gather_facts: false
  vars:
    gh_ws: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}"
    pkg_name: 'htop'
    config: '{{ gh_ws }}/repo/pkgs/{{ pkg_name }}/config.yml'
  tasks:
    - name: Install pkg-repo-tools
      ansible.builtin.pip:
        name: file://{{ gh_ws }}/repo/.github/assets

    - name: Create Directories
      ansible.builtin.file:
        path: "{{ gh_ws }}/dist"
        state: directory
        recurse: true
        mode: '0755'

    - name: Get external pkg for redistribution
      ansible.builtin.shell:
        cmd: |
          pkg-tool redistribute-pkg {{ config }} \
            --abi ${ABI} --arch ${ARCH}
        chdir: "{{ gh_ws }}/dist"
        creates: "{{ gh_ws }}/dist/packagesite_info.json"
