---
- name: Build UpSnap
  hosts: localhost
  gather_facts: false
  vars:
    gh_ws: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}"
    repo: 'seriousm4x/UpSnap'
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ gh_ws }}/dist"
        state: directory
        mode: '0755'

    - name: Get latest release of a public repository
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl -s https://api.github.com/repos/{{ repo }}/releases/latest | jq -r '.tag_name'
        executable: /bin/bash
      register: latest_release
      changed_when: latest_release.rc != 0

    - name: Git checkout repository
      ansible.builtin.git:
        repo: 'https://github.com/{{ repo }}.git'
        dest: "{{ gh_ws }}/src"
        version: "{{ latest_release.stdout }}"

    - name: Build UpSnap frontend
      ansible.builtin.shell:
        cmd: |
          npm i -g pnpm
          pnpm --prefix=./frontend i
          pnpm --prefix=./frontend run build
          cp -r ./frontend/build/* ./backend/pb_public/
        chdir: "{{ gh_ws }}/src"
        creates: "{{ gh_ws }}/src/backend/pb_public/"

    - name: Build UpSnap backend
      ansible.builtin.shell:
        cmd: |
          go mod tidy
          go build
          mv upsnap ${GITHUB_WORKSPACE}/dist
        chdir: "{{ gh_ws }}/src/backend"
        creates: "{{ gh_ws }}/dist/upsnap"
      environment:
        GOOS: freebsd
        GOARCH: "{{ lookup('env', 'ARCH',) }}"
        CGO_ENABLED: '0'
