---
- name: Build UpSnap
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist"
        state: directory
        mode: '0755'

    - name: Get latest release of a public repository
      community.general.github_release:
        user: seriousm4x
        repo: UpSnap
        action: latest_release
      register: latest_release

    - name: Download and Extract UpSnap source
      ansible.builtin.unarchive:
        src: https://github.com/seriousm4x/UpSnap/archive/refs/tags/{{ latest_release.tag }}.tar.gz
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}"
        remote_src: true

    - name: Move UpSnap source
      ansible.builtin.shell:
        cmd: mv $GITHUB_WORKSPACE/UpSnap-{{ latest_release.tag }} $GITHUB_WORKSPACE/src
        creates: "{{ lookup('env', 'NODEBIN',) }}"

    - name: Build UpSnap
      ansible.builtin.shell:
        cmd: |
          npm i -g pnpm
          pnpm --prefix=./frontend i
          pnpm --prefix=./frontend run build
          cp -r ./frontend/build/* ./backend/pb_public/
          cd backend
          go mod tidy
          go build
          mv upsnap ${GITHUB_WORKSPACE}/dist
        chdir: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        creates: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist/upsnap"
      environment:
        GOOS: freebsd
        GOARCH: "{{ lookup('env', 'ARCH',) }}"
        CGO_ENABLED: 0
