---
- name: Build UpSnap
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist"
        state: directory
        mode: '0755'

    - name: Get latest release of a public repository
      ansible.builtin.shell:
        cmd: gh release --repo seriousm4x/UpSnap list --json tagName,isLatest --jq '.[] | select(.isLatest)|.tagName'
      register: latest_release

    - name: Git checkout UpSnap
      ansible.builtin.git:
        repo: 'https://github.com/seriousm4x/UpSnap.git'
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        version: "{{ latest_release.stdout }}"

    - name: Build UpSnap
      ansible.builtin.shell:
        cmd: |
          npm i -g pnpm
          pnpm --prefix=./frontend i
          pnpm --prefix=./frontend run build
          cp -r ./frontend/build/* ./backend/pb_public/
          cd backend
          go mod tidy
          go build
          mv upsnap ${GITHUB_WORKSPACE}/dist
        chdir: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        creates: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist/upsnap"
      environment:
        GOOS: freebsd
        GOARCH: "{{ lookup('env', 'ARCH',) }}"
        CGO_ENABLED: 0
