---
- name: Build CaddyV2
  hosts: localhost
  gather_facts: false
  vars:
    go_version: 1.23.5
    caddy_plugins:
      - github.com/caddy-dns/porkbun
      - github.com/caddy-dns/ddnss
      - github.com/mietzen/caddy-dynamicdns-cmd-source
  environment:
    PATH: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/go/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/go"
        - "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        - "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist"

    - name: Download and Extract Go
      ansible.builtin.unarchive:
        src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/go"
        remote_src: true

    - name: Get latest release of CaddyV2
      community.general.github_release:
        user: caddyserver
        repo: caddy
        action: latest_release
      register: latest_release

    - name: Download and Extract CaddyV2 source
      ansible.builtin.unarchive:
        src: "https://github.com/caddyserver/caddy/archive/refs/tags/{{ latest_release.tag }}.tar.gz"
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        remote_src: true

    - name: Install xCaddy
      ansible.builtin.shell:
        cmd: |
          which go
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Build CaddyV2
      ansible.builtin.shell:
        cmd: |
          which go
          echo $PATH
          GOOS=freebsd \
          GOARCH={{ lookup('env', 'ARCH',) }} \
          {{ lookup('env', 'GITHUB_WORKSPACE',) }}/go/bin/xcaddy build {{ latest_release.tag }} \
            --with {{ caddy_plugins | join(' --with ') }} \
            --output {{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist
        chdir: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        creates: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist/caddy"

