---
- name: Build CaddyV2
  hosts: localhost
  gather_facts: false
  vars:
    caddy_plugins:
      - github.com/caddy-dns/porkbun
      - github.com/caddy-dns/ddnss
      - github.com/mietzen/caddy-dynamicdns-cmd-source
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist"
        state: directory
        mode: '0755'

    - name: Get latest release of a public repository
      ansible.builtin.shell:
        cmd: gh release --repo caddyserver/xcaddy list --json tagName,isLatest --jq '.[] | select(.isLatest)|.tagName'
      register: latest_release

    - name: Install xCaddy
      ansible.builtin.shell:
        cmd: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
        creates: "{{ lookup('env', 'GOBIN',) }}/xcaddy"

    - name: Build CaddyV2
      ansible.builtin.shell:
        cmd: |
          xcaddy build {{ latest_release.stdout }} \
              --with {{ caddy_plugins | join(' --with ') }} \
              --output $GITHUB_WORKSPACE/dist
        creates: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist/caddy"
      environment:
        GOOS: freebsd
        GOARCH: "{{ lookup('env', 'ARCH',) }}"
