---
- name: Build CaddyV2
  hosts: localhost
  gather_facts: false
  vars:
    go_version: 1.23.5
    caddy_plugins:
      - github.com/caddy-dns/porkbun
      - github.com/caddy-dns/ddnss
      - github.com/mietzen/caddy-dynamicdns-cmd-source
  environment:
    GOPATH: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/go"
    GOBIN: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/go/bin"

  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist"
        state: directory
        mode: '0755'

    - name: Download and Extract Go
      ansible.builtin.unarchive:
        src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}"
        remote_src: true

    - name: Get latest release of CaddyV2
      community.general.github_release:
        user: caddyserver
        repo: caddy
        action: latest_release
      register: latest_release

    - name: Install xCaddy
      ansible.builtin.shell:
        cmd: |
          ${GOBIN}/go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
        creates: "{{ lookup('env', 'GOBIN',) }}/xcaddy"

    - name: Build CaddyV2
      ansible.builtin.shell:
        cmd: |
          ${GOBIN}/xcaddy build {{ latest_release.tag }} \
              --with {{ caddy_plugins | join(' --with ') }} \
              --output $GITHUB_WORKSPACE/dist
        chdir: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        creates: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist/caddy"
      environment:
        GOOS: freebsd
        GOARCH: "{{ lookup('env', 'ARCH',) }}"
