---
- name: Build Traefik
  hosts: localhost
  gather_facts: false
  vars:
    gh_ws: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}"
    repo: 'traefik/traefik'
    pkg_name: 'traefik'
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ gh_ws }}/dist"
        state: directory
        recurse: true
        mode: '0755'

    - name: Get latest release of a public repository
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl -s https://api.github.com/repos/{{ repo }}/releases/latest | jq -r '.tag_name'
        executable: /bin/bash
      register: latest_release
      changed_when: latest_release.rc != 0

    - name: Git checkout repository
      ansible.builtin.git:
        repo: 'https://github.com/{{ repo }}.git'
        dest: "{{ gh_ws }}/src"
        version: "{{ latest_release.stdout }}"

    - name: Build Binary
      ansible.builtin.shell:
        cmd: |
          go get github.com/containous/go-bindata/...
          go generate
          go build ./cmd/traefik
        chdir: "{{ gh_ws }}/src"
        creates: "{{ gh_ws }}/src/{{ pkg_name }}"
      environment:
        GOOS: freebsd
        GOARCH: "{{ lookup('env', 'ARCH',) }}"
        GO111MODULE: 'on'

    - name: Create Directories
      ansible.builtin.file:
        path: "{{ gh_ws }}/dist/pkg/{{ item }}"
        state: directory
        recurse: true
        mode: '0755'
      loop:
        - 'opt/{{ pkg_name }}'
        - 'etc/rc.d'

    - name: Copy Binary
      ansible.builtin.copy:
        src: "{{ gh_ws }}/src/{{ pkg_name }}"
        dest: "{{ gh_ws }}/dist/pkg/opt/{{ pkg_name }}/{{ pkg_name }}"
        remote_src: true
        mode: '0755'

    - name: Create Service
      ansible.builtin.shell:
        cmd: |
          python {{ gh_ws }}/repo/.github/assets/create-service.py
        chdir: "{{ gh_ws }}/dist/pkg/etc/rc.d/"
        creates: "{{ gh_ws }}/dist/pkg/etc/rc.d/{{ pkg_name }}"

    - name: Create Manifest
      ansible.builtin.shell:
        cmd: |
          python {{ gh_ws }}/repo/.github/assets/create-manifest.py
        chdir: "{{ gh_ws }}/dist/pkg"
        creates: "{{ gh_ws }}/dist/pkg/+MANIFEST"

    - name: Create PKG
      community.general.archive:
        path: "{{ gh_ws }}/dist/pkg/*"
        dest: "{{ gh_ws }}/dist/{{ pkg_name }}.pkg"
        format: xz
        mode: '755'

    - name: Remove intermediate PKG Folder
      ansible.builtin.file:
        path: "{{ gh_ws }}/dist/pkg"
        state: absent
