---
build_config:
  include: {}
  src_repo: 'https://github.com/mietzen/opnsense_leases_widget'
pkg_manifest:
  name: opnsense_leases_widget
  origin: mietzen/opnsense_leases_widget
  version: 24.07
  comment: A DHCP Leases Widget for OPNsense
  www: https://github.com/jbaconsult/opnsense_stuff
  maintainer: github.nstein@mailbox.org
  prefix: /opt/yq
  licenselogic: single
  licenses:
    - GPL-3.0 license
  desc: |
    A DHCP Leases Widget for OPNsense
  scripts:
    post-install: |
      sed -i '' -e '/<\/metadata>/ {
          r /tmp/opnsense_leases_widget/Core.xml
          d
      }' /usr/local/opnsense/www/js/widgets/Metadata/Core.xml
      echo "</metadata>" >> /usr/local/opnsense/www/js/widgets/Metadata/Core.xml
      rm -rf /tmp/opnsense_leases_widget/Core.xml
    post-deinstall: |
      sed -i '' -e '/<leases>/,/<\/leases>/d' /usr/local/opnsense/www/js/widgets/Metadata/Core.xml
