---
build_config:
  include:
    go: '1.23'
pkg_manifest:
  name: traefik
  origin: mietzen/traefik
  version: 3.3.3
  comment: The Cloud Native Application Proxy
  www: https://traefik.io
  maintainer: github.nstein@mailbox.org
  prefix: /opt/traefik
  users:
    - traefik
  groups:
    - www
  licenselogic: single
  licenses:
    -  MIT license
  desc: |
    Traefik (pronounced traffic) is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
    Traefik integrates with your existing infrastructure components:
      Docker, Swarm mode, Kubernetes, Consul, Etcd, Rancher v2, Amazon ECS
    and configures itself automatically and dynamically.
    Pointing Traefik at your orchestrator should be the only configuration step you need.
  scripts:
    pre-install: |
      existing_ids=$(mktemp)
      cut -d: -f3,4 /etc/passwd | tr ':' '\n' | sort -un > $existing_ids
      service_id=$(seq 100 999 | grep -vxFf $existing_ids | tail -n1)
      rm $existing_ids
      mkdir -p /opt/traefik
      pw adduser traefik -u $service_id -d /opt/traefik -s /usr/sbin/nologin -c "traefik service user"
      chown -R traefik:www /opt/traefik
    post-install: |
      /etc/rc.d/traefik enable
      /etc/rc.d/traefik start
    pre-deinstall: |
      /etc/rc.d/traefik stop
      /etc/rc.d/traefik disable
    post-deinstall: |
      pw deluser traefik
      sysrc -x traefik_enable
pkg_service:
  template: default
  vars:
    COMMAND: /opt/traefik/traefik --configFile=./config.yml
