---
build_config:
  include:
    go: '1.23'
    src_repo: 'https://github.com/traefik/traefik'
pkg_manifest:
  name: traefik
  origin: mietzen/traefik
  version: 3.3.4
  comment: The Cloud Native Application Proxy
  www: https://traefik.io
  maintainer: github.nstein@mailbox.org
  prefix: /opt/traefik
  users:
    - traefik
  groups:
    - traefik
  licenselogic: single
  licenses:
    - MIT license
  desc: |
    Traefik (pronounced traffic) is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
    Traefik integrates with your existing infrastructure components:
      Docker, Swarm mode, Kubernetes, Consul, Etcd, Rancher v2, Amazon ECS
    and configures itself automatically and dynamically.
    Pointing Traefik at your orchestrator should be the only configuration step you need.
  scripts:
    pre-install: |
      existing_ids=$(mktemp)
      cut -d: -f3,4 /etc/passwd | tr ':' '\n' | sort -un > $existing_ids
      service_id=$(seq 300 999 | grep -vxFf $existing_ids | head -n1)
      rm $existing_ids
      echo "===> Creating user"
      if ! pw usershow traefik >/dev/null 2>&1; then
        pw adduser traefik -u $service_id -d /nonexistent -s /usr/sbin/nologin -c "traefik service user"
      else
        echo "Using existing user 'traefik'"
      fi
    post-install: |
      chown -R traefik:www /opt/traefik
      echo "===> Starting service"
      service traefik enable
      service traefik start
    pre-deinstall: |
      echo "===> Stopping service"
      service traefik stop
      service traefik disable
    post-deinstall: |
      echo "===> Deleting user"
      pw deluser traefik
pkg_service:
  template: default
  vars:
    COMMAND: /opt/traefik/traefik --configFile=./config.yml
