---
build_config:
  include:
    go: '1.23'
    node: '22'
pkg_manifest:
  name: upsnap
  origin: mietzen/upsnap
  version: 4.6.1
  comment: A simple wake on lan web app written with SvelteKit, Go and PocketBase.
  www: https://github.com/seriousm4x/UpSnap
  maintainer: github.nstein@mailbox.org
  prefix: /opt/upsnap
  users:
    - upsnap
  groups:
    - www
  licenselogic: single
  licenses:
    -  MIT license
  desc: |
    UpSnap provides an intuitive dashboard to wake devices with one click, schedule timed events, and scan networks for devices.
    Built with SvelteKit, Go, and PocketBase, it supports secure user management, multi-language support, and customizable themes.
    Ideal for self-hosting with Docker or binary options, it integrates features like port pinging and network discovery.
    While offering powerful functionality, it's recommended to use VPN for external access due to security.
  deps:
    nmap:
      origin: security/nmap
      version: "7.94_3"
  scripts:
    pre-install: |
      existing_ids=$(mktemp)
      cut -d: -f3,4 /etc/passwd | tr ':' '\n' | sort -un > $existing_ids
      service_id=$(seq 100 999 | grep -vxFf $existing_ids | tail -n1)
      rm $existing_ids
      mkdir -p /opt/upsnap
      pw adduser upsnap -u $service_id -d /opt/upsnap -s /usr/sbin/nologin -c "upsnap service user"
      chown -R upsnap:www /opt/upsnap
    post-install: |
      /etc/rc.d/upsnap enable
      /etc/rc.d/upsnap start
    pre-deinstall: |
      /etc/rc.d/upsnap stop
      /etc/rc.d/upsnap disable
    post-deinstall: |
      pw deluser upsnap
      sysrc -x upsnap_enable
pkg_service:
  template: default
  vars:
    COMMAND: /opt/upsnap/upsnap --dir /opt/upsnap serve --http=127.0.0.1:8090
