---
build_config:
  include:
    go: '1.23'
    node: '22'
  src_repo: 'https://github.com/seriousm4x/UpSnap'
pkg_manifest:
  name: upsnap
  origin: opnware/upsnap
  version: 5.1.1
  comment: A simple wake on lan web app written with SvelteKit, Go and PocketBase.
  www: https://github.com/seriousm4x/UpSnap
  maintainer: github.nstein@mailbox.org
  prefix: /opt/opnware/pkgs/upsnap
  users:
    - upsnap
  groups:
    - upsnap
  licenselogic: single
  licenses:
    -  MIT license
  desc: |
    UpSnap provides an intuitive dashboard to wake devices with one click, schedule timed events, and scan networks for devices.
    Built with SvelteKit, Go, and PocketBase, it supports secure user management, multi-language support, and customizable themes.
    Ideal for self-hosting with Docker or binary options, it integrates features like port pinging and network discovery.
    While offering powerful functionality, it's recommended to use VPN for external access due to security.
  deps:
    nmap:
      origin: security/nmap
      version: "7.94_3"
  scripts:
    pre-install: |
      existing_ids=$(mktemp)
      cut -d: -f3,4 /etc/passwd | tr ':' '\n' | sort -un > $existing_ids
      service_id=$(seq 300 999 | grep -vxFf $existing_ids | head -n1)
      rm $existing_ids
      echo "===> Creating user"
      if ! pw usershow upsnap >/dev/null 2>&1; then
        pw adduser upsnap -u $service_id -d /nonexistent -s /usr/sbin/nologin -c "upsnap service user"
      else
        echo "Using existing user 'upsnap'"
      fi
    post-install: |
      chown -R upsnap:www /opt/opnware/pkgs/upsnap
      echo "===> Starting service"
      service upsnap enable
      service upsnap start
    pre-deinstall: |
      echo "===> Stopping service"
      service upsnap stop
      service upsnap disable
    post-deinstall: |
      echo "===> Deleting user"
      pw deluser upsnap
pkg_service:
  template: default
  vars:
    COMMAND: /opt/opnware/pkgs/upsnap/upsnap --dir /opt/opnware/pkgs/upsnap serve --http=127.0.0.1:8090
