[start]
command:/usr/sbin/service podman start
type:script
message:Starting Podman service

[stop]
command:/usr/sbin/service podman stop
type:script
message:Stopping Podman service

[restart]
command:/usr/sbin/service podman restart
type:script
message:Restarting Podman service

[status]
command:/usr/sbin/service podman status; exit 0
type:script_output
message:Checking Podman status

[setup]
command:/usr/local/bin/php /usr/local/opnsense/scripts/OPNsense/Podman/setup.php
type:script_output
message:Running Podman environment setup

[containers.list]
command:/usr/local/opnsense/scripts/OPNsense/Podman/manage.py containers.list
type:script_output
message:Listing containers

[containers.start]
command:/usr/local/opnsense/scripts/OPNsense/Podman/manage.py containers.start
parameters:%s
type:script_output
message:Starting container %s

[containers.stop]
command:/usr/local/opnsense/scripts/OPNsense/Podman/manage.py containers.stop
parameters:%s
type:script_output
message:Stopping container %s

[containers.kill]
command:/usr/local/opnsense/scripts/OPNsense/Podman/manage.py containers.kill
parameters:%s
type:script_output
message:Killing container %s

[containers.restart]
command:/usr/local/opnsense/scripts/OPNsense/Podman/manage.py containers.restart
parameters:%s
type:script_output
message:Restarting container %s

[images.list]
command:/usr/local/opnsense/scripts/OPNsense/Podman/manage.py images.list
type:script_output
message:Listing container images

[volumes.list]
command:/usr/local/opnsense/scripts/OPNsense/Podman/manage.py volumes.list
type:script_output
message:Listing container volumes

[networks.list]
command:/usr/local/opnsense/scripts/OPNsense/Podman/manage.py networks.list
type:script_output
message:Listing container networks
