[status]
command:/usr/sbin/service terminal-service status; exit 0
type:script_output
message:get terminal service status

[start]
command:/usr/sbin/service terminal-service start
type:script
message:start terminal service

[stop]
command:/usr/sbin/service terminal-service stop
type:script
message:stop terminal service

[restart]
command:/usr/sbin/service terminal-service restart
type:script
message:restart terminal service

[shell_status]
command:/usr/local/bin/php /usr/local/opnsense/scripts/OPNsense/Terminal/shell_status.php
type:script_output
message:get shell statuses

[install_bash]
command:/usr/local/sbin/pkg install -y bash
type:script_output
message:install bash package

[install_zsh]
command:/usr/local/sbin/pkg install -y zsh
type:script_output
message:install zsh package
