http:
  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$apr1$JXeu5FR/$BCBTuybb/RZK1NawhGOcZ0" # admin:admin
  routers:
    api:
      rule: "HostRegexp(`.+`)"
      entrypoints:
       - web
      middlewares:
       - dashboard-auth
      service: api@internal