guest="linux"
loader="uefi"
cpu={{ OPNsense.docker.general.cpus|default('2') }}
memory={{ OPNsense.docker.general.memory|default('2048') }}M
network0_type="virtio-net"
network0_switch="docker-net"
disk0_type="virtio-blk"
disk0_name="os.img"
disk1_type="virtio-blk"
disk1_name="data.img"
utctime="yes"
