---
build_config:
  include:
    node: '22'
  src_repo: 'https://github.com/bastienwirtz/homer'
pkg_manifest:
  name: homer
  origin: opnware/homer
  version: 25.10.1
  comment: A very simple static homepage for your server.
  www: https://homer-demo.netlify.app/
  maintainer: github.nstein@mailbox.org
  prefix: /opt/opnware/pkgs/caddy/conf.d/homer
  licenselogic: single
  licenses:
    - APACHE20
  desc: |
    Homer is a dead simple static HOMepage for your servER (or anything else) to keep your services and favorite links on hand,
    based on a simple yaml configuration file. Learn more at https://github.com/bastienwirtz/homer
  deps:
    caddy:
      origin: opnware/caddy
      version: ">=2.9.1, <3.0.0"
  post-install: |
    chown -R caddy:www /opt/opnware/pkgs/caddy/conf.d/homer
    chown -R caddy:www /opt/opnware/pkgs/caddy/conf.d/homer.caddy