[start]
command:service homer start
parameters:
type:script
message:Starting Homer service

[stop]
command:service homer stop
parameters:
type:script
message:Stopping Homer service

[restart]
command:service homer restart
parameters:
type:script
message:Restarting Homer service
description:Restart Homer service

[reload]
command:service homer reload
parameters:
type:script
message:Reloading Homer service
description:Reload Homer service

[status]
command:/usr/local/sbin/pluginctl -s homer status
parameters:
type:script_output
message:Request Homer status

[config-save]
command:/usr/local/bin/php /usr/local/opnsense/scripts/OPNsense/Homer/config_save.php
parameters:
type:script_output
message:Saving Homer config
description:Validate and atomically apply the staged Homer config.yml
