---
- name: Build AdGuardHome
  hosts: localhost
  gather_facts: false
  vars:
    gh_ws: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}"
    repo: 'AdguardTeam/AdGuardHome'
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ gh_ws }}/dist"
        state: directory
        mode: '0755'

    - name: Install snapcraft
      ansible.builtin.command:
        cmd: snap install snapcraft --classic
        creates: "/snap/bin/snapcraft"
      become: true

    - name: Get latest release of a public repository
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl -s https://api.github.com/repos/{{ repo }}/releases/latest | jq -r '.tag_name'
        executable: /bin/bash
      register: latest_release
      changed_when: latest_release.rc != 0

    - name: Git checkout repository
      ansible.builtin.git:
        repo: 'https://github.com/{{ repo }}.git'
        dest: "{{ gh_ws }}/src"
        version: "{{ latest_release.stdout }}"

    - name: Build AdGuardHome
      community.general.make:
        chdir: "{{ gh_ws }}/src"
        target: build-release
        params:
          VERBOSE: 1
          CHANNEL: release
          SIGN: 0
          VERSION: "{{ latest_release.stdout }}"
          DIST_DIR: "../dist"
          ARCH: "{{ lookup('env', 'ARCH',) }}"
          OS: freebsd
