---
- name: Build AdGuardHome
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist"
        state: directory
        mode: '0755'

    - name: Get latest release of a public repository
      ansible.builtin.shell:
        cmd: gh release --repo AdguardTeam/AdGuardHome list --json tagName,isLatest --jq '.[] | select(.isLatest)|.tagName'
      register: latest_release

    - name: Install snapcraft
      ansible.builtin.shell:
        cmd: snap install snapcraft --classic
        creates: "/snap/bin/snapcraft"
      become: true

    - name: Git checkout AdGuardHome
      ansible.builtin.git:
        repo: 'https://github.com/AdguardTeam/AdGuardHome.git'
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        version: "{{ latest_release.stdout }}"

    - name: Build AdGuardHome
      community.general.make:
        chdir: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        target: build-release
        params:
          VERBOSE: 1
          CHANNEL: release
          SIGN: 0
          VERSION: "{{ latest_release.tag }}"
          DIST_DIR: "../dist"
          ARCH: "{{ lookup('env', 'ARCH',) }}"
          OS: freebsd
