---
- name: Build AdGuardHome
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist"
        state: directory
        mode: '0755'

    - name: Get latest release of a public repository
      community.general.github_release:
        user: AdguardTeam
        repo: AdGuardHome
        action: latest_release
      register: latest_release

    - name: Move UpSnap source
      ansible.builtin.shell:
        cmd: |
          snap install snapcraft --classic
          which snapcraft
      become: true

    - name: Download and Extract AdGuardHome source
      ansible.builtin.unarchive:
        src: https://github.com/AdguardTeam/AdGuardHome/archive/refs/tags/{{ latest_release.tag }}.tar.gz
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}"
        remote_src: true

    - name: Move AdGuardHome source
      ansible.builtin.shell:
        cmd: mv $GITHUB_WORKSPACE/AdGuardHome-{{ latest_release.tag[1:] }} $GITHUB_WORKSPACE/src
        creates: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"

    - name: Build AdGuardHome
      community.general.make:
        chdir: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/src"
        target: build-release
        params:
          VERBOSE: 1
          CHANNEL: release
          SIGN: 0
          VERSION: "{{ latest_release.tag }}"
          DIST_DIR: "{{ lookup('env', 'GITHUB_WORKSPACE',) }}/dist"
          ARCH: "{{ lookup('env', 'ARCH',) }}"
          OS: freebsd
