name: Update Workflow Caller

on:
  workflow_dispatch:
  push:
    paths:
      - 'pkg-src/**'


jobs:
  generate-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ steps.generate-token.outputs.token }}
      
      - name: Get GitHub App User ID
        id: get-user-id
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      
      - name: Set Commiter Credentials
        run: |
          git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      
      - name: Discover Packages
        id: discover
        run: |
          # Find all packages with a build_pkg.yml and manifest.yml
          packages=$(find pkg-src -type f -name "build_pkg.yml" -exec dirname {} \; | xargs -n1 basename | sed -z '$ s/\n$//' | jq -Rsc 'split("\n")')
          if [ -z $packages ]; then
            echo "No packages found! $packages"
            echo "packages=''" >> $GITHUB_ENV
          else
            echo "Found packages: $packages"
            echo "packages=$packages" >> $GITHUB_ENV
          fi

      - name: Generate Workflow
        id: generate
        if: ${{ steps.discover.outputs.packages }} != ''
        run: |
          cat <<EOF > .github/workflows/workflow_caller.yml
          ######################################################
          #            GENERATED FILE DON'T CHANGE!            #
          ######################################################
          # This file is generated by update_workflow_caller.yml
          name: Workflow caller

          on:
            workflow_call:
              inputs:
                abi:
                  required: true
                  type: string
                arch:
                  required: true
                  type: string
                pkg_name:
                  required: true
                  type: string

          jobs:
            build:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout Code
                  uses: actions/checkout@v3
          EOF
          echo "" >> .github/workflows/workflow_caller.yml

          rm -rf .github/workflows/build_*.yml
          echo "${packages}" | jq -r '.[]' | while read -r pkg; do
            reusable_workflow="./.github/workflows/build_${pkg}.yml"
            cat << EOL >> .github/workflows/workflow_caller.yml
                - name: ${pkg}
                  if: inputs.pkg_name == '${pkg}'
                  uses: ${reusable_workflow}
                  with:
                    abi: ${{ '\${{ inputs.abi }}' }}
                    arch: ${{ '\${{ inputs.arch }}' }}
          EOL
            echo "" >> .github/workflows/workflow_caller.yml
            cat << EOF > ${reusable_workflow}
          ######################################################
          #            GENERATED FILE DON'T CHANGE!            #
          ######################################################
          # This file is generated by update_workflow_caller.yml
          `cat ./pkg-src/${pkg}/build_pkg.yml`
          EOF
            git add ${reusable_workflow}
            git commit -m "Copied ${pkg} workflow" || echo "No changes in ${reusable_workflow}"
          done

          git add .github/workflows/.
          git commit -m "Removed old workflows" || echo "No old workflows to remove"

          git add .github/workflows/workflow_caller.yml
          git commit -m "Updated package workflow caller" || echo "No changes in .github/workflows/workflow_caller.yml"

          echo ""
          echo "Workflow generated."
          echo "-------------------"
          cat .github/workflows/workflow_caller.yml
          echo ""

          git push
