name: Workflow caller

on:
  workflow_call:
    inputs:
      abi:
        required: true
        type: string
      arch:
        required: true
        type: string
      pkg_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: upsnap
        if: inputs.pkg_name == 'upsnap'
        uses: ./.github/workflows/build_upsnap.yml
        with:
          abi: ${{ inputs.abi }}
          arch: ${{ inputs.arch }}

