# syslog-ng fragment for OPNware os-podman
destination d_podman {
    file(
        "/var/log/podman/podman_${YEAR}${MONTH}${DAY}.log"
        create_dirs(yes)
        template(t_opnsense)
    );
};

filter f_podman {
    program("podman") or facility(local4);
};

log {
    source(s_all);
    filter(f_podman);
    destination(d_podman);
};
